package cz.legat.core.model

enum class Countries(val id: Int, val country: String) {
    AFGHANSKA(3, "afghánská"),
    ALBANSKA(137, "albánská"),
    ALZIRSKA(7, "alžírská"),
    AMERICKA(79, "americká"),
    ANDORRSKA(101, "andorrská"),
    ANGLICKA(1, "anglická"),
    ANGOLSKA(4, "angolská"),
    ARABSKA(152, "arabská"),
    ARGENTINSKA(5, "argentinská"),
    ARMENSKA(109, "arménská"),
    AUSTRALSKA(2, "australská"),
    AZERBAJDZANSKA(6, "ázerbájdžánská"),
    BANGLADESSKA(129, "bangladešská"),
    BARMSKA(139, "barmská"),
    BELGICKA(8, "belgická"),
    BENGALSKA(12, "bengálská"),
    BENINSKA(141, "beninská"),
    BHUTANSKA(148, "bhútánská"),
    BOLIVIJSKA(111, "bolivijská"),
    BOSENSKOHERCEGOVSKA(11, "bosenskohercegovská"),
    BRAZILSKA(9, "brazilská"),
    BRITSKA(80, "britská"),
    BULHARSKA(10, "bulharská"),
    BURUNDSKA(158, "burundská"),
    CECENSKA(113, "čečenská"),
    CERNOHORSKA(87, "černohorská"),
    CESKA(13, "česká"),
    CINSKA(15, "čínská"),
    DANSKA(16, "dánská"),
    DOMINIKANSKA(128, "dominikánská"),
    EGYPTSKA(17, "egyptská"),
    EKVADORSKA(135, "ekvádorská"),
    ESTONSKA(18, "estonská"),
    ETIOPSKA(103, "etiopská"),
    FILIPINSKA(155, "filipínská"),
    FINSKA(20, "finská"),
    FRANCOUZSKA(19, "francouzská"),
    GHANSKA(22, "ghanská"),
    GRONSKA(24, "grónská"),
    GRUZINSKA(21, "gruzínská"),
    GUATEMALSKA(147, "guatemalská"),
    GUINEJSKA(23, "guinejská"),
    HAITSKA(132, "haitská"),
    HONGKONGSKA(138, "hongkongská"),
    CHILSKA(26, "chilská"),
    CHORVATSKA(27, "chorvatská"),
    INDICKA(30, "indická"),
    INDONESKA(98, "indonéská"),
    IRACKA(33, "irácká"),
    IRANSKA(32, "íránská"),
    IRSKA(85, "irská"),
    ISLANDSKA(31, "islandská"),
    ITALSKA(28, "italská"),
    IVORIANSKA(100,"ivorianská (Pobřeží slonoviny)"),
    IZRAELSKA(29,"izraelská"),
    JAMAJSKA(123,"jamajská"),
    JAPONSKA(35,"japonská"),
    JIHOAFRICKA(37,"jihoafrická"),
    JIHOKOREJSKA(34,"jihokorejská"),
    JORDANSKA(120,"jordánská"),
    JUGOSLAVSKA(36,"jugoslávská"),
    KAMBODZSKA(99,"kambodžská"),
    KAMERUNSKA(146,"kamerunská"),
    KANADSKA(40,"kanadská"),
    KAPVERDSKA(142,"kapverdská"),
    KASMIRSKA(143,"kašmírská"),
    KAZASSKA(93,"kazašská"),
    KENSKA(116,"keňská"),
    KIRGIZSKA(153,"kirgizská"),
    KOLUMBIJSKA(106,"kolumbijská"),
    KONZSKA(127,"konžská"),
    KOSTARICKA(105,"kostarická"),
    KUBANSKA(39,"kubánská"),
    KUVAJTSKA(154,"kuvajtská"),
    KYPERSKA(140,"kyperská"),
    LIBANONSKA(41,"libanonská"),
    LIBYJSKA(121,"libyjská"),
    LITEVSKA(92,"litevská"),
    LOTYSSKA(91,"lotyšská"),
    LUCEMBURSKA(42,"lucemburská"),
    LUZICKOSRBSKA(159,"lužickosrbská"),
    MADARSKA(47,"maďarská"),
    MAKEDONSKA(125,"makedonská"),
    MALAJSKA(118,"malajská"),
    MALLORSKA(145,"mallorská"),
    MALTSKA(46,"maltská"),
    MAROCKA(43,"marocká"),
    MARTINICKA(44,"martinická"),
    MAURITANSKA(149,"mauritánská"),
    MEXICKA(45,"mexická"),
    MOLDAVSKA(130,"moldavská"),
    MONGOLSKA(115,"mongolská"),
    MOSAMBICKA(133,"mosambická"),
    NEMECKA(52,"německá"),
    NEPALSKA(119,"nepálská"),
    NIGERIJSKA(50,"nigerijská"),
    NIKARAGUJSKA(49,"nikaragujská"),
    NIZOZEMSKA(86,"nizozemská"),
    NORSKA(51,"norská"),
    NOVOZELANDSKA(48,"novozélandská"),
    PAKISTANSKA(53,"pákistánská"),
    PALESTINSKA(56,"palestinská"),
    PANAMSKA(156,"panamská"),
    PARAGUAYSKA(104,"paraguayská"),
    PERSKA(55,"perská"),
    PERUANSKA(54,"peruánská"),
    POLSKA(58,"polská"),
    PORTORICKA(114,"portorická"),
    PORTUGALSKA(57,"portugalská"),
    RAKOUSKA(59,"rakouská"),
    RAKOUSKO_UHERSKA(117,"rakousko-uherská"),
    RHODESKA(61,"rhodeská"),
    RUMUNSKA(60,"rumunská"),
    RUSKA(62,"ruská"),
    RWANDSKA(96,"rwandská"),
    RECKA(63,"řecká"),
    SALVADORSKA(144,"salvadorská"),
    SAUDSKOARABSKA(94,"saúdskoarabská"),
    SENEGALSKA(90,"senegalská"),
    SEVEROIRSKA(157,"severoirská"),
    SEVEROKOREJSKA(88,"severokorejská"),
    SINGAPURSKA(134,"singapurská"),
    SKOTSKA(70,"skotská"),
    SLOVENSKA(64,"slovenská"),
    SLOVINSKA(65,"slovinská"),
    SOMALSKA(67,"somálská"),
    SRBSKA(69,"srbská"),
    SRILANSKA(71,"srílanská"),
    SUDANSKA(122,"súdánská"),
    SYRSKA(66,"syrská"),
    SPANELSKA(72,"španělská"),
    SVEDSKA(84,"švédská"),
    SVYCARSKA(73,"švýcarská"),
    TADZICKA(150,"tádžická"),
    THAJSKA(124,"thajská"),
    TIBETSKA(97,"tibetská"),
    TRINIDADSKA(75,"trinidadská"),
    TUNISKA(108,"tuniská"),
    TURECKA(74,"turecká"),
    TURKMENISTANSKA(95,"turkmenistánská"),
    UGANDSKA(78,"ugandská"),
    UKRAJINSKA(77,"ukrajinská"),
    URUGUAYSKA(76,"uruguayská"),
    UZBEKISTANSKA(136,"uzbekistánská"),
    VELSSKA(83,"velšská"),
    VENEZUELSKA(81,"venezuelská"),
    VIETNAMSKA(82,"vietnamská"),
    ZAMBIJSKA(151,"zambijská"),
    ZIMBABWSKA(126,"zimbabwská")
}